### ISSUE TITLE
[suggestion] Can I get more data?

### ISSUE THREAD

**Issue by 44578287** [lemutec/PresentMonFps#1]
PresentMon itself can also acquire a wealth of data, such as rendering API time, CPU time, GPU time, and more.
Maybe it's possible to customize the sampling speed like Intel PresentMon as well?

**Comment by emako** [comment]
I understand what you mean, but this lib focuses on detecting the FPS of the game, rather than the complete functions of PresentMon, that’s why it’s called PresentMonFps.
So therefore there are no plans to add these features.
